---
# argument spec file for andersson007.adt_test.run

argument_specs:
  main:
    short_description: Role description.
    options:
      my_variable:
        type: str
        description: A simple string argument for demonstration.
        default: "default_value"
